config/routes.rb
Rails.application.routes.draw do
  resources :friendships

  resources :users do
    collection do
      get :index_json
    end
  end

  resources :salaries
  resources :performances
  resources :announcements
  resources :materials
  resources :articles
  resources :departments
  resources :companynews
  resources :vacation

  resources :messages do
    collection do
      delete :destroyall
    end
  end

  resources :chats do
    member do
      patch :trans_auth
      post :add_user
      delete :delete_user
    end
  end

  resources :friendships

  root 'homes#home'

  
  post 'sessions/login' => 'sessions#login'
  delete 'sessions/logout' => 'sessions#destroy'

end

app/views/layouts/_content.html.erb
<script type="text/javascript">
    toastr.options = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": false,
        "progressBar": true,
        "positionClass": "toast-bottom-right",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    };

    <% flash.each do |message_type,message| %>
    <% message_type = 'error'   if message_type == 'danger'%>
    toastr['<%= message_type %>']('<%= message %>');
    <% end %>
</script>

<br>
<div class="container-fluid">
  <%= yield %>
</div>


<%# flash.each do |message_type, message| %>
<!--<div class="alert alert-<%#= message_type %>">-->
<!--<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>-->
<!--<strong> <%#= message %></strong>-->
<!--</div>-->
<%# end %>

app/views/layouts/_footer.html.erb
<div class="row" style="padding-top: 60px; clear: both;">
   <div class="col-md-12 text-center"><p><small>&copy; All Rights Reserved. <a href="http://www.ucas.ac.cn/" title = "UCAS" target="_blank">UCAS</a> - Based on <a href="https://github.com/PENGZhaoqing/RailsChat" title="RailsChat" target="_blank">RailsChat</a>. Many thanks to <a href="https://github.com/PENGZhaoqing" title="PENGZhaoqing" target="_blank">PENGZhaoqing</a></small></p>
   </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">

    <div class="navbar-header">
      <%= link_to root_path, class: 'navbar-brand', style: "color:white" do %>
          <i class="fa fa-leaf" aria-hidden="true"></i> 网上聊天室
      <% end %>
    </div>

    <ul class="nav navbar-nav navbar-right">

      <% if current_user %>

          <!-- <li>
            <%= link_to chats_path, class: "dropbtn" do %>
                 进入聊天 <i class="fa fa-wechat"></i>
            <% end %>
          </li> -->

          <li>
            <%= link_to user_path(current_user), method: :get, class: "dropbtn" do %>
                <%= current_user.name %> <span class="glyphicon glyphicon-user"></span>
            <% end %>
          </li>

          <li>
            <%= link_to sessions_logout_path, method: :delete, class: "dropbtn" do %>
                退出 <span class="	glyphicon glyphicon-off"></span>
            <% end %>
          </li>

      <% end %>
    </ul>
  </div>
  </div>
</nav>

app/views/layouts/_login_panel.html.erb
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-md-offset-4">

          <!-- Start Sign In Form -->
          <!-- form action="#" class="fh5co-form animate-box" data-animate-effect="fadeInLeft" -->
            <%= form_for(:session, url: sessions_login_path, method: :post, html: {:role=>'form', :class=>'fh5co-form animate-box'}) do |f| %>
              <h2>SIGN IN</h2>
              <div class="form-group">
                <label for="username" class="sr-only"></label>
                <%= f.email_field :email, class: 'form-control', placeholder: "输入邮箱" %>
              </div>
              <div class="form-group">
                <label for="password" class="sr-only">Password</label>
                <%= f.password_field :password, class: 'form-control', placeholder: "输入密码" %>
              </div>
              <div class="form-group">
                <label for="remember"><%= f.check_box :remember_me %>记住我</label>
              </div>
              <div class="form-group">
                <p> 未注册? <%= link_to users_path, method: :post do %>注册<% end %>|<a href="#">忘记密码</a></p>
              </div>
              <div class="form-group">
                <%= button_tag(type: "submit", class: "btn btn-primary btn-block") do %>
                <span class="glyphicon glyphicon-off"></span> 登录 <% end %>
              </div>
            <% end %>
          <!-- /form -- >
          <!-- END Sign In Form -->

        </div>
      </div>
    </div>

app/views/layouts/_signup_panel.html.erb
<!-- Modal -->
<div class="modal fade" id="panel_modal_signup" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header" style="padding:35px 50px;">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4><span class="glyphicon glyphicon-lock"></span> 注册</h4>
      </div>
      <div class="modal-body" style="padding:40px 50px;">

        <%= form_for(:session, url: users_create_path, method: :post, html: {role: 'form'}) do |f| %>

            <div class="form-group">
              <%= f.label :email, "请填写详细信息：" %>
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                <%= f.text_field :name, class: 'form-control', placeholder: "输入用户名" %>
              </div>
            </div>
            
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></div>
                <%= f.email_field :email, class: 'form-control', placeholder: "输入邮箱" %>
              </div>
            </div>
            
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                <%= f.password_field :password, class: 'form-control', placeholder: "输入密码" %>
              </div>
            </div>
            
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-earphone"></span></div>
                <%= f.number_field :phonenumber, class: 'form-control', placeholder: "输入电话号码" %>
              </div>
            </div>

            <div class="checkbox">
              <label><%= f.check_box :remember_me %>记住我</label>
            </div>

            <%= button_tag(type: "submit", class: "btn btn-primary btn-block") do %>
                <span class="glyphicon glyphicon-off"></span> 注册
            <% end %>

        <% end %>
      </div>

      <div class="modal-footer">
        <p class="text-center">已有账号? 请登录</p>
      </div>

    </div>

  </div>

</div>

<script>
  $(document).ready(function () {
    $("#signup_panel").click(function (e) {
      e.preventDefault();
      $("#panel_modal_signup").modal();
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>欢迎来到网上聊天室!</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= include_sync_config %>
  <meta>
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= csrf_meta_tags %>
</head>

	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

<body class="style-2">

<%= render partial: 'layouts/header' %>
<%= render partial: 'layouts/content' %>
<%= render partial: 'layouts/footer' %>

</body>
</html>